# These are supported funding model platforms
patreon: 'ZhiyuanLck'
custom: ['paypal.me/ZhiyuanLck', 'github.com/ZhiyuanLck/images/blob/master/sponsor/alipay.jpg', 'github.com/ZhiyuanLck/images/blob/master/sponsor/wechat.png']
